# Site settings
title: Course Website
subtitle: Title of the Course
description: |
    When we talk about Machine Learning (ML), we typically refer to a technique or an algorithm that gives the computer systems the ability to learn and to reason with data. However, there is a lot more to ML than just implementing an algorithm or a technique. In this course, we will learn the fundamental differences between ML as a technique versus ML as a system in production. A machine learning system involves a significant number of components and it is important that they remain responsive in the face of failure and changes in load. This course covers several strategies to keep ML systems responsive, resilient, and elastic. Machine learning systems are different than other computer systems when it comes to building, testing, deploying, delivering, and evolving. ML systems also have unique challenges when we need to change the architecture or behavior of the system. Therefore, it is essential to learn how to deal with such unique challenges that only may happen when building real-world production-ready ML systems (e.g., performance issues, memory leaking, communication issues, multi-GPU issues, etc). The focus of this course will be primarily on deep learning systems, but the principles will remain similar across all ML systems. 
 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://pooyanjamshidi.github.io/mls/" # the base hostname & protocol for your site
syllabus: "https://github.com/pooyanjamshidi/mls/blob/master/desc/mls.pdf"
githubdir: ""

# Author/user information
email: pjamshid@cse.sc.edu
twitter_username: pooyanjamshidi
github_username:  pooyanjamshidi
authorurl: "https://pooyanjamshidi.github.io"
address: |
    2207


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: "